'use server'

import { getServerSession } from 'next-auth'
import { authOptions } from '@/app/api/auth/[...nextauth]/route'
import { prisma } from '@/lib/prisma'
import { revalidatePath } from 'next/cache'

// -----------------------------------------------------------------------------
// 1. CREATE BLUEPRINT & GENERATE MOCKS
// -----------------------------------------------------------------------------
export async function createBlueprintAction(formData: FormData) {
  const session = await getServerSession(authOptions)
  if (!session?.user) return { error: 'Unauthorized' }
  
  // 1. Parse Form Data
  const course_id = formData.get('course_id') as string
  const title = formData.get('title') as string
  const duration = parseInt(formData.get('duration') as string) || 60
  const total_marks = parseInt(formData.get('marks') as string) || 100
  const sets_count = Math.min(Math.max(parseInt(formData.get('sets_count') as string) || 3, 1), 20)
  
  // Marking Scheme
  const marks_correct = parseFloat(formData.get('marks_correct') as string) || 4
  const marks_incorrect = parseFloat(formData.get('marks_incorrect') as string) || -1
  const marks_unattempted = parseFloat(formData.get('marks_unattempted') as string) || 0

  const subjectCounts = parseSubjectCounts(formData)

  if (subjectCounts.length === 0) {
    return { error: 'Please specify question count for at least one subject.' }
  }

  try {
    // 2. Insert Blueprint Header
    const blueprint = await prisma.mock_blueprints.create({
      data: {
        course_id,
        title,
        total_duration_minutes: duration,
        total_marks: total_marks
      }
    })

    // 3. Insert Blueprint Items (Rules)
    const items = subjectCounts.map(item => ({
      blueprint_id: blueprint.id,
      subject_id: item.subjectId,
      question_count: item.count
    }))

    if (items.length > 0) {
      await prisma.mock_blueprint_items.createMany({ data: items })
    }

    // 4. AUTO-GENERATE MOCKS
    const result = await generateBulkMocks(blueprint, items, { 
      marks_correct, 
      marks_incorrect, 
      marks_unattempted 
    }, sets_count)

    revalidatePath('/dashboard/admin/blueprints')
    revalidatePath('/dashboard/admin/mocktest') 
    revalidatePath(`/courses/${course_id}`)

    if (typeof result === 'object' && result !== null && 'error' in result) {
      return { success: true, generatedCount: 0, warning: result.error }
    }

    return { success: true, generatedCount: result as number }
  } catch (error: any) {
    return { error: `Blueprint creation failed: ${error.message}` }
  }
}

// -----------------------------------------------------------------------------
// 2. UPDATE BLUEPRINT & RE-GENERATE MOCKS
// -----------------------------------------------------------------------------
export async function updateBlueprintAction(formData: FormData) {
  const session = await getServerSession(authOptions)
  if (!session?.user) return { error: 'Unauthorized' }
  
  const id = formData.get('id') as string
  const title = formData.get('title') as string
  const duration = parseInt(formData.get('duration') as string) || 60
  const total_marks = parseInt(formData.get('marks') as string) || 100
  const sets_count = Math.min(Math.max(parseInt(formData.get('sets_count') as string) || 3, 1), 20)

  const marks_correct = parseFloat(formData.get('marks_correct') as string) || 4
  const marks_incorrect = parseFloat(formData.get('marks_incorrect') as string) || -1
  const marks_unattempted = parseFloat(formData.get('marks_unattempted') as string) || 0
  
  const subjectCounts = parseSubjectCounts(formData)

  if (subjectCounts.length === 0) {
    return { error: 'Please specify question count for at least one subject.' }
  }

  try {
    const existingBp = await prisma.mock_blueprints.findUnique({ where: { id } })
    if (!existingBp) return { error: 'Blueprint not found' }

    // Clean up old mock tests generated by this blueprint to free questions and avoid stale sets
    const oldMocks = await prisma.mock_tests.findMany({
      where: {
        course_id: existingBp.course_id,
        subject_id: null,
        OR: [
          { description: { contains: existingBp.title } },
          { title: { startsWith: existingBp.title } }
        ]
      },
      select: { id: true }
    })

    if (oldMocks.length > 0) {
      const oldMockIds = oldMocks.map(m => m.id)
      await prisma.mock_test_questions.deleteMany({ where: { mock_test_id: { in: oldMockIds } } })
      await prisma.mock_tests.deleteMany({ where: { id: { in: oldMockIds } } })
    }

    // 1. Update Header
    const blueprint = await prisma.mock_blueprints.update({
      where: { id },
      data: {
        title,
        total_duration_minutes: duration,
        total_marks: total_marks
      }
    })

    // 2. Update Items (Delete Old -> Insert New)
    await prisma.mock_blueprint_items.deleteMany({ where: { blueprint_id: id } })

    const items = subjectCounts.map(item => ({
      blueprint_id: id,
      subject_id: item.subjectId,
      question_count: item.count
    }))

    if (items.length > 0) {
      await prisma.mock_blueprint_items.createMany({ data: items })
    }

    // 3. AUTO-GENERATE MOCKS
    const result = await generateBulkMocks(blueprint, items, {
      marks_correct, 
      marks_incorrect, 
      marks_unattempted 
    }, sets_count)

    revalidatePath('/dashboard/admin/blueprints')
    revalidatePath('/dashboard/admin/mocktest')
    revalidatePath(`/courses/${blueprint.course_id}`)

    if (typeof result === 'object' && result !== null && 'error' in result) {
      return { success: true, generatedCount: 0, warning: result.error }
    }

    return { success: true, generatedCount: result as number }
  } catch (error: any) {
    return { error: error.message }
  }
}

// -----------------------------------------------------------------------------
// 3. DELETE BLUEPRINT & CLEAN UP GENERATED MOCKS
// -----------------------------------------------------------------------------
export async function deleteBlueprintAction(id: string) {
  const session = await getServerSession(authOptions)
  if (!session?.user) return { error: 'Unauthorized' }

  try {
    const bp = await prisma.mock_blueprints.findUnique({ where: { id } })
    if (bp) {
      // Find tests generated by this blueprint
      const generatedMocks = await prisma.mock_tests.findMany({
        where: { 
          course_id: bp.course_id,
          subject_id: null,
          OR: [
            { description: { contains: bp.title } },
            { title: { startsWith: bp.title } }
          ]
        },
        select: { id: true }
      })
      if (generatedMocks.length > 0) {
        const mIds = generatedMocks.map(m => m.id)
        await prisma.mock_test_questions.deleteMany({ where: { mock_test_id: { in: mIds } } })
        await prisma.mock_tests.deleteMany({ where: { id: { in: mIds } } })
      }
    }

    await prisma.mock_blueprints.delete({ where: { id } })
    revalidatePath('/dashboard/admin/blueprints')
    revalidatePath('/dashboard/admin/mocktest')
    return { success: true }
  } catch (error: any) {
    return { error: error.message }
  }
}

// -----------------------------------------------------------------------------
// INTERNAL: BULK MOCK GENERATOR
// -----------------------------------------------------------------------------
async function generateBulkMocks(
  blueprint: any, 
  items: any[], 
  markingScheme: { marks_correct: number, marks_incorrect: number, marks_unattempted: number },
  setsToGenerate: number = 3
) {
  const errors: string[] = []

  // 1. Identify "Used" Questions in other Exam Mocks of this course
  const otherExamMocks = await prisma.mock_tests.findMany({
    where: { 
      course_id: blueprint.course_id,
      subject_id: null 
    },
    select: { id: true }
  })

  let usedQuestionIds = new Set<string>()

  if (otherExamMocks && otherExamMocks.length > 0) {
    const mockIds = otherExamMocks.map(m => m.id)
    const usedQuestions = await prisma.mock_test_questions.findMany({
      where: { mock_test_id: { in: mockIds } },
      select: { question_id: true }
    })
    
    usedQuestions.forEach(q => usedQuestionIds.add(q.question_id))
  }

  // 2. Prepare Question Pools per Subject
  const subjectFullPool: Record<string, string[]> = {}
  const subjectUnusedPool: Record<string, string[]> = {}

  for (const item of items) {
    if (item.question_count <= 0) continue

    // A. Get Question Banks for Subject
    const banks = await prisma.question_banks.findMany({
      where: { subject_id: item.subject_id },
      select: { id: true }
    })
    const bankIds = banks.map(b => b.id)

    // B. Fetch All Questions for this Subject (both via question_bank and direct subject_id)
    const questions = await prisma.questions.findMany({
      where: {
        OR: [
          ...(bankIds.length > 0 ? [{ question_bank_id: { in: bankIds } }] : []),
          { subject_id: item.subject_id }
        ]
      },
      select: { id: true }
    })

    const allIds = questions.map(q => q.id)
    
    if (allIds.length === 0) {
      const sub = await prisma.subjects.findUnique({
        where: { id: item.subject_id },
        select: { title: true }
      })
      errors.push(`Subject "${sub?.title || item.subject_id}" has no questions in the database.`)
      continue
    }

    if (allIds.length < item.question_count) {
      const sub = await prisma.subjects.findUnique({
        where: { id: item.subject_id },
        select: { title: true }
      })
      errors.push(`Subject "${sub?.title || item.subject_id}" has only ${allIds.length} question(s), but ${item.question_count} required per test.`)
      continue
    }

    // Unused pool for this subject
    const unusedIds = allIds.filter(id => !usedQuestionIds.has(id))

    // Shuffle both pools
    subjectFullPool[item.subject_id] = [...allIds].sort(() => 0.5 - Math.random())
    subjectUnusedPool[item.subject_id] = [...unusedIds].sort(() => 0.5 - Math.random())
  }

  if (errors.length > 0) {
    return { error: errors.join(' ') }
  }

  // 3. Determine how many tests to generate
  const numTests = Math.max(1, Math.min(setsToGenerate, 20))
  let testsCreated = 0

  // 4. Generation Loop
  for (let i = 0; i < numTests; i++) {
    const timestamp = new Date().getTime().toString().slice(-4)
    const mockTitle = `${blueprint.title} - Set ${i + 1} (${timestamp})`
    
    try {
      // A. Create Mock Header (Exam-Wise)
      const mockTest = await prisma.mock_tests.create({
        data: {
          title: mockTitle,
          description: `Full syllabus mock generated from ${blueprint.title}.`,
          course_id: blueprint.course_id,
          subject_id: null, // NULL = Exam-Wise Mock
          
          duration_minutes: blueprint.total_duration_minutes,
          total_marks: blueprint.total_marks,
          
          marks_correct: markingScheme.marks_correct,
          marks_incorrect: markingScheme.marks_incorrect,
          marks_unattempted: markingScheme.marks_unattempted,
          
          is_active: true
        },
        select: { id: true }
      })

      // B. Allocate Questions
      let allQuestionsForMock: any[] = []
      
      for (const item of items) {
        if (item.question_count <= 0) continue
        
        const countNeeded = item.question_count
        const unusedPool = subjectUnusedPool[item.subject_id] || []
        const fullPool = subjectFullPool[item.subject_id] || []

        let selectedIds: string[] = []

        if (unusedPool.length >= countNeeded) {
          // Take directly from unused pool
          selectedIds = unusedPool.splice(0, countNeeded)
        } else {
          // Take whatever unused questions remain
          selectedIds = unusedPool.splice(0, unusedPool.length)
          const remainingNeeded = countNeeded - selectedIds.length

          // Sample remainder from fullPool without duplicates in this test
          const availableInFull = fullPool.filter(id => !selectedIds.includes(id))
          const shuffledAvailable = [...availableInFull].sort(() => 0.5 - Math.random())
          const sampled = shuffledAvailable.slice(0, remainingNeeded)
          
          selectedIds = [...selectedIds, ...sampled]
        }
        
        if (selectedIds.length > 0) {
          const links = selectedIds.map(qid => ({
            mock_test_id: mockTest.id,
            question_id: qid
          }))
          allQuestionsForMock = [...allQuestionsForMock, ...links]
        }
      }

      // C. Save Links
      if (allQuestionsForMock.length > 0) {
        await prisma.mock_test_questions.createMany({ data: allQuestionsForMock })
        testsCreated++
      }
    } catch (error) {
      console.error("Failed to create mock_test iteration", i, error)
      continue
    }
  }

  return testsCreated
}

// --- HELPER ---
function parseSubjectCounts(formData: FormData) {
  const subjectCounts: { subjectId: string, count: number }[] = []
  for (const [key, value] of formData.entries()) {
    if (key.startsWith('subject_count_') && Number(value) > 0) {
      subjectCounts.push({
        subjectId: key.replace('subject_count_', ''),
        count: Number(value)
      })
    }
  }
  return subjectCounts
}